version: '1'

services:
  email-to-sms-gateway:
    image: sphexi/email-to-sms-gateway
    environment:
      - EMAIL_USER=<email account login>
      - EMAIL_PASS=<email account password>
      - EMAIL_SERVER=<pop3 server url>
      - VOIP_USER=<voip.ms username>
      - VOIP_PASS=<voip.ms api password>
      - VOIP_DID=<voip.ms did>
      - MAIN_DST=<non-emergency number to text>
      - EMERGENCY_DST=<csv of emergency numbers to text>
    restart: unless-stopped